name: Docker Image Build

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghrc.io/noordsestern/score-humanitec:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}