name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: noordsestern/score-humanitec:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ github.token }}